services:
  haruyasumi_ryokouki:
    build: .
    container_name: haruyasumi_ryokouki
    deploy:
      resources:
        limits:
          memory: 1536Mb
          cpus: "4"
    ports:
      - "5104:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
