// <auto-generated />
using System;
using HaruyasumiRyokouki.Backend.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HaruyasumiRyokouki.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722104147_AddInitialArchiveSchema")]
    partial class AddInitialArchiveSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready");

                    b.HasKey("Id")
                        .HasName("pk_days");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("ix_days_date");

                    b.ToTable("days", (string)null);
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.DayTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DayId")
                        .HasColumnType("integer")
                        .HasColumnName("day_id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.HasKey("Id")
                        .HasName("pk_day_translations");

                    b.HasIndex("Note")
                        .HasDatabaseName("ix_day_translations_note");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Note"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Note"), new[] { "gin_trgm_ops" });

                    b.HasIndex("DayId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_day_translations_day_id_language_code");

                    b.ToTable("day_translations", (string)null);
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<int>("DayId")
                        .HasColumnType("integer")
                        .HasColumnName("day_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approved");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_media_files");

                    b.HasIndex("DayId")
                        .HasDatabaseName("ix_media_files_day_id");

                    b.ToTable("media_files", (string)null);
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_file_id");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_media_translations");

                    b.HasIndex("Description")
                        .HasDatabaseName("ix_media_translations_description");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Description"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Description"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_media_translations_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_media_translations_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("MediaFileId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_media_translations_media_file_id_language_code");

                    b.ToTable("media_translations", (string)null);
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.DayTranslation", b =>
                {
                    b.HasOne("HaruyasumiRyokouki.Backend.Models.Db.Day", "Day")
                        .WithMany("Translations")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_day_translations_days_day_id");

                    b.Navigation("Day");
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaFile", b =>
                {
                    b.HasOne("HaruyasumiRyokouki.Backend.Models.Db.Day", "Day")
                        .WithMany("Media")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_files_days_day_id");

                    b.Navigation("Day");
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaTranslation", b =>
                {
                    b.HasOne("HaruyasumiRyokouki.Backend.Models.Db.MediaFile", "MediaFile")
                        .WithMany("Translations")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_translations_media_files_media_file_id");

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.Day", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaFile", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
