// <auto-generated />
using System;
using HaruyasumiRyokouki.Backend.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HaruyasumiRyokouki.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815120534_AddMediaEmbeddings")]
    partial class AddMediaEmbeddings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready");

                    b.HasKey("Id")
                        .HasName("pk_days");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("ix_days_date");

                    b.ToTable("days", (string)null);
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.DayTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayId")
                        .HasColumnType("integer")
                        .HasColumnName("day_id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.HasKey("Id")
                        .HasName("pk_day_translations");

                    b.HasIndex("Note")
                        .HasDatabaseName("ix_day_translations_note");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Note"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Note"), new[] { "gin_trgm_ops" });

                    b.HasIndex("DayId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_day_translations_day_id_language_code");

                    b.ToTable("day_translations", (string)null);
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaEmbedding", b =>
                {
                    b.Property<int>("MediaFileId")
                        .HasColumnType("integer")
                        .HasColumnName("media_file_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.PrimitiveCollection<float[]>("Vector")
                        .IsRequired()
                        .HasColumnType("real[]")
                        .HasColumnName("vector");

                    b.HasKey("MediaFileId")
                        .HasName("pk_media_embeddings");

                    b.ToTable("media_embeddings", (string)null);
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string[]>("AdditionalFiles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("additional_files");

                    b.Property<float>("AspectRatio")
                        .HasColumnType("real")
                        .HasColumnName("aspect_ratio");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<int>("DayId")
                        .HasColumnType("integer")
                        .HasColumnName("day_id");

                    b.Property<bool>("Favorite")
                        .HasColumnType("boolean")
                        .HasColumnName("favorite");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approved");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Miniature")
                        .HasColumnType("text")
                        .HasColumnName("miniature");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean")
                        .HasColumnName("private");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_media_files");

                    b.HasIndex("DayId")
                        .HasDatabaseName("ix_media_files_day_id");

                    b.ToTable("media_files", (string)null);
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaFileTag", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("MediaId", "TagId")
                        .HasName("pk_media_file_tag");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_media_file_tag_tag_id");

                    b.ToTable("media_file_tag", (string)null);
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("integer")
                        .HasColumnName("media_file_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_media_translations");

                    b.HasIndex("Description")
                        .HasDatabaseName("ix_media_translations_description");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Description"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Description"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_media_translations_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("MediaFileId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_media_translations_media_file_id_language_code");

                    b.ToTable("media_translations", (string)null);
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.TagTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_tag_translations");

                    b.HasIndex("Text")
                        .HasDatabaseName("ix_tag_translations_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Text"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Text"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TagId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ux_tag_labels_primary_per_language")
                        .HasFilter("is_primary");

                    b.HasIndex("TagId", "Text")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_translations_tag_id_text");

                    b.ToTable("tag_translations", (string)null);
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.DayTranslation", b =>
                {
                    b.HasOne("HaruyasumiRyokouki.Backend.Models.Db.Day", "Day")
                        .WithMany("Translations")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_day_translations_days_day_id");

                    b.Navigation("Day");
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaEmbedding", b =>
                {
                    b.HasOne("HaruyasumiRyokouki.Backend.Models.Db.MediaFile", "MediaFile")
                        .WithOne()
                        .HasForeignKey("HaruyasumiRyokouki.Backend.Models.Db.MediaEmbedding", "MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_embeddings_media_files_media_file_id");

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaFile", b =>
                {
                    b.HasOne("HaruyasumiRyokouki.Backend.Models.Db.Day", "Day")
                        .WithMany("Media")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_files_days_day_id");

                    b.Navigation("Day");
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaFileTag", b =>
                {
                    b.HasOne("HaruyasumiRyokouki.Backend.Models.Db.MediaFile", "Media")
                        .WithMany("MediaTags")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_file_tag_media_files_media_id");

                    b.HasOne("HaruyasumiRyokouki.Backend.Models.Db.Tag", "Tag")
                        .WithMany("MediaTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_file_tag_tags_tag_id");

                    b.Navigation("Media");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaTranslation", b =>
                {
                    b.HasOne("HaruyasumiRyokouki.Backend.Models.Db.MediaFile", "MediaFile")
                        .WithMany("Translations")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_translations_media_files_media_file_id");

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.TagTranslation", b =>
                {
                    b.HasOne("HaruyasumiRyokouki.Backend.Models.Db.Tag", "Tag")
                        .WithMany("Translations")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_translations_tags_tag_id");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.Day", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.MediaFile", b =>
                {
                    b.Navigation("MediaTags");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("HaruyasumiRyokouki.Backend.Models.Db.Tag", b =>
                {
                    b.Navigation("MediaTags");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
